### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20,) + inhomogeneous part.

### ISSUE THREAD

**Issue by ynareshkalyan21** [ynareshkalyan21/CarModel#1]
/Users/yarramsettinaresh/envCar/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 49263 --file /Users/yarramsettinaresh/PycharmProjects/CarModel/positional_pattern_model.py
-------------------------------------------------------------------------------
pydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807
-------------------------------------------------------------------------------
Connected to pydev debugger (build 221.6008.17)
pydev debugger: Unable to find real location for: <frozen codecs>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap_external>
pydev debugger: Unable to find real location for: <frozen zipimport>
pydev debugger: Unable to find real location for: <frozen _collections_abc>
pydev debugger: Unable to find real location for: <frozen os>
pydev debugger: Unable to find real location for: <frozen abc>
pydev debugger: Unable to find real location for: <frozen importlib.util>
pydev debugger: Unable to find real location for: <frozen posixpath>
pydev debugger: Unable to find real location for: <string>
pydev debugger: Unable to find real location for: <frozen genericpath>
pydev debugger: Unable to find real location for: <frozen io>
pydev debugger: Unable to find real location for: <frozen site>
pydev debugger: Unable to find real location for: <decorator-gen-0>
pydev debugger: Unable to find real location for: config-3.py
dict_keys(['major_parts', 'MAJOR_PARTS_NO_DIRECTION', 'CATEGORY_MAPP', 'CATEGORY_RULES'])
pydev debugger: Unable to find real location for: <frozen runpy>
pydev debugger: Unable to find real location for: <decorator-gen-1>
pydev debugger: Unable to find real location for: <decorator-gen-2>
pydev debugger: Unable to find real location for: <decorator-gen-3>
pydev debugger: Unable to find real location for: <decorator-gen-4>
<dataset_utils.CategoryHandler object at 0x1790f9110>

=== Dataset Analysis ===

Total images processed: 20
Total valid images: -15
Total empty images: 15
No parts images: 0

TRAIN Split:
  Total images: 0

VAL Split:
  Total images: 0

TEST Split:
  Total images: 0
Masks shape: (20, 256, 256)
Positions shape: (5, 2)
Part labels shape: (5, 19)
Category: 2
Model: "functional"
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ part_masks          │ (None, 20, 640,   │          0 │ -                 │
│ (InputLayer)        │ 640, 1)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 20, 638,   │        320 │ part_masks[0][0]  │
│ (TimeDistributed)   │ 638, 32)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_1  │ (None, 20, 319,   │          0 │ time_distributed… │
│ (TimeDistributed)   │ 319, 32)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_2  │ (None, 20, 317,   │     18,496 │ time_distributed… │
│ (TimeDistributed)   │ 317, 64)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_3  │ (None, 20, 158,   │          0 │ time_distributed… │
│ (TimeDistributed)   │ 158, 64)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_4  │ (None, 20,        │          0 │ time_distributed… │
│ (TimeDistributed)   │ 1597696)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_5  │ (None, 20, 128)   │ 204,505,2… │ time_distributed… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ part_positions      │ (None, 20, 2)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ part_labels         │ (None, 20, 19)    │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 2560)      │          0 │ time_distributed… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_2 (Flatten) │ (None, 40)        │          0 │ part_positions[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_3 (Flatten) │ (None, 380)       │          0 │ part_labels[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │    327,808 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 128)       │      5,248 │ flatten_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     48,768 │ flatten_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 384)       │          0 │ dense_1[0][0],    │
│ (Concatenate)       │                   │            │ dense_2[0][0],    │
│                     │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ category_output     │ (None, 7)         │      2,695 │ concatenate[0][0] │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘
 Total params: 204,908,551 (781.66 MB)
 Trainable params: 204,908,551 (781.66 MB)
 Non-trainable params: 0 (0.00 B)
(20, 256, 256)
(20, 256, 256)
Backend macosx is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yarramsettinaresh/PycharmProjects/CarModel/positional_pattern_model.py", line 164, in <module>
    train_positions = np.array(train_positions)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20,) + inhomogeneous part.
python-BaseException

Process finished with exit code 1

**Comment by ynareshkalyan21** [comment]
/Users/yarramsettinaresh/envCar/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 49475 --file /Users/yarramsettinaresh/PycharmProjects/CarModel/positional_pattern_model.py
-------------------------------------------------------------------------------
pydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807
-------------------------------------------------------------------------------
Connected to pydev debugger (build 221.6008.17)
pydev debugger: Unable to find real location for: <frozen codecs>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap>
pydev debugger: Unable to find real location for: <frozen importlib._bootstrap_external>
pydev debugger: Unable to find real location for: <frozen zipimport>
pydev debugger: Unable to find real location for: <frozen _collections_abc>
pydev debugger: Unable to find real location for: <frozen os>
pydev debugger: Unable to find real location for: <frozen abc>
pydev debugger: Unable to find real location for: <frozen importlib.util>
pydev debugger: Unable to find real location for: <frozen posixpath>
pydev debugger: Unable to find real location for: <string>
pydev debugger: Unable to find real location for: <frozen genericpath>
pydev debugger: Unable to find real location for: <frozen io>
pydev debugger: Unable to find real location for: <frozen site>
pydev debugger: Unable to find real location for: <decorator-gen-0>
pydev debugger: Unable to find real location for: config-3.py
dict_keys(['major_parts', 'MAJOR_PARTS_NO_DIRECTION', 'CATEGORY_MAPP', 'CATEGORY_RULES'])
pydev debugger: Unable to find real location for: <frozen runpy>
pydev debugger: Unable to find real location for: <decorator-gen-1>
pydev debugger: Unable to find real location for: <decorator-gen-2>
pydev debugger: Unable to find real location for: <decorator-gen-3>
pydev debugger: Unable to find real location for: <decorator-gen-4>
<dataset_utils.CategoryHandler object at 0x177bf94d0>

=== Dataset Analysis ===

Total images processed: 20
Total valid images: -15
Total empty images: 15
No parts images: 0

TRAIN Split:
  Total images: 0

VAL Split:
  Total images: 0

TEST Split:
  Total images: 0
Model: "functional"
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ part_masks          │ (None, 20, 640,   │          0 │ -                 │
│ (InputLayer)        │ 640, 1)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast (Cast)         │ (None, 20, 640,   │          0 │ part_masks[0][0]  │
│                     │ 640, 1)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 20, 256,   │          0 │ cast[0][0]        │
│ (TimeDistributed)   │ 256, 1)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_1  │ (None, 20, 254,   │        160 │ time_distributed… │
│ (TimeDistributed)   │ 254, 16)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_2  │ (None, 20, 127,   │          0 │ time_distributed… │
│ (TimeDistributed)   │ 127, 16)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_3  │ (None, 20, 125,   │      9,280 │ time_distributed… │
│ (TimeDistributed)   │ 125, 64)          │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_4  │ (None, 20, 62,    │          0 │ time_distributed… │
│ (TimeDistributed)   │ 62, 64)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_5  │ (None, 20,        │          0 │ time_distributed… │
│ (TimeDistributed)   │ 246016)           │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ part_positions      │ (None, 20, 2)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ part_labels         │ (None, 20, 19)    │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_6  │ (None, 20, 128)   │ 31,490,176 │ time_distributed… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_1 (Cast)       │ (None, 20, 2)     │          0 │ part_positions[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_2 (Cast)       │ (None, 20, 19)    │          0 │ part_labels[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 2560)      │          0 │ time_distributed… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_2 (Flatten) │ (None, 40)        │          0 │ cast_1[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_3 (Flatten) │ (None, 380)       │          0 │ cast_2[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 128)       │    327,808 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 128)       │      5,248 │ flatten_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     48,768 │ flatten_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 384)       │          0 │ dense_1[0][0],    │
│ (Concatenate)       │                   │            │ dense_2[0][0],    │
│                     │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ category_output     │ (None, 7)         │      2,695 │ concatenate[0][0] │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘
 Total params: 31,884,135 (121.63 MB)
 Trainable params: 31,884,135 (121.63 MB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 29s 5s/step - accuracy: 0.2229 - loss: 1.9794
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 23s 5s/step - accuracy: 0.5188 - loss: 1.5521
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - accuracy: 0.2153 - loss: 1.4053
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - accuracy: 0.4896 - loss: 1.3067
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 23s 5s/step - accuracy: 0.6306 - loss: 1.2420
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 25s 5s/step - accuracy: 0.5701 - loss: 1.1757
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - accuracy: 0.6361 - loss: 1.0329
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - accuracy: 0.7507 - loss: 0.8212
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 24s 5s/step - accuracy: 0.8556 - loss: 0.7255
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 1059s 263s/step - accuracy: 0.9833 - loss: 0.5977
Backend macosx is interactive backend. Turning interactive mode on.

Process finished with exit code 0
